name: test
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 0 * * 0"
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-2
  TF_IN_AUTOMATION: true
  TF_INPUT: false
jobs:
  main:
    runs-on: ubuntu-latest
    container: codecache/terraform:0.14.6
    steps:
      - uses: actions/checkout@v2
      - name: init
        run: terraform init test
      - name: import
        run: |
          TF_VAR_git=$(git remote get-url origin | sed -e 's|.*/||' | sed -e 's|.git$||')
          terraform import module.this.aws_s3_bucket.this ${TF_VAR_git} test || true
          terraform import module.this.aws_s3_bucket_public_access_block.this ${TF_VAR_git} test || true
      - name: apply
        run: |
          TF_VAR_git=$(git remote get-url origin | sed -e 's|.*/||' | sed -e 's|.git$||')
          terraform apply -auto-approve test
      - name: idempotency
        run: |
          TF_VAR_git=$(git remote get-url origin | sed -e 's|.*/||' | sed -e 's|.git$||')
          terraform plan -detailed-exitcode test
      - name: destroy
        run: |
          TF_VAR_git=$(git remote get-url origin | sed -e 's|.*/||' | sed -e 's|.git$||')
          terraform destroy -auto-approve test
      - name: destroy idempotency
        run: |
          TF_VAR_git=$(git remote get-url origin | sed -e 's|.*/||' | sed -e 's|.git$||')
          terraform destroy test
      - name: lint
        run: terraform fmt -recursive -check
